URL = "https://au.jora.com"
SERVICE_NAME = "jora"

JORA_STATES = {
    "NSW": "New South Wales",
    "QLD": "Queensland",
    "TAS": "Tasmania",
    "WA": "Western Australia",
    "NT": "Northern Territory",
    "SA": "South Australia",
    "VIC": "Victoria",
    "ACT": "Australian Capital Territory",
}

JORA_ATTRIBUTES = {
    "jobTitle": "jobtitle",
    "jobCompany": "company",
    "jobLocation": "location",
    "jobShortDescription": "summary",
    "jobListingDate": "date",
    "salary": "salary",
}

JORA_CATEGORIES = [
    "Accounting",
    "Administrative",
    "Agriculture",
    "Architecture",
    "Arts",
    "Banking",
    "Business",
    "Computer",
    "Construction",
    "Consulting",
    "Customer Service",
    "Education",
    "Energy",
    "Engineering",
    "Facilities",
    "Finance",
    "Food Service",
    "Healthcare",
    "Hospitality",
    "Human Resources",
    "IT",
    "Law Enforcement",
    "Legal",
    "Logistics",
    "Maintenance",
    "Management",
    "Manufacturing",
    "Marketing",
    "Mechanical",
    "Mining",
    "Pharmaceutical",
    "Publishing",
    "Real Estate",
    "Restaurant",
    "Retail",
    "Sales",
    "Scientific",
    "Security",
    "Social Care",
    "Sport",
    "Training",
    "Transportation",
    "Travel",
    "Volunteering",
]
