URL = "https://www.seek.com.au/"
SERVICE_NAME = "seek"

SEEK_LINK = {
    "Accounting": "jobs-in-accounting",
    "Administration & Office Support": "jobs-in-administration-office-support",
    "Advertising, Arts & Media": "jobs-in-advertising-arts-media",
    "Banking & Financial Services": "jobs-in-banking-financial-services",
    "Call Centre & Customer Service": "jobs-in-call-centre-customer-service",
    "CEO & General Management": "jobs-in-ceo-general-management",
    "Community Services & Development": "jobs-in-community-services-development",
    "Construction": "jobs-in-construction",
    "Consulting & Strategy": "jobs-in-consulting-strategy",
    "Design & Architecture": "jobs-in-design-architecture",
    "Education & Training": "jobs-in-education-training",
    "Engineering": "jobs-in-engineering",
    "Farming, Animals & Conservation": "jobs-in-farming-animals-conservation",
    "Government & Defence": "jobs-in-government-defence",
    "Healthcare & Medical": "jobs-in-healthcare-medical",
    "Hospitality & Tourism": "jobs-in-hospitality-tourism",
    "Human Resources & Recruitment": "jobs-in-human-resources-recruitment",
    "Information & Communication Technology": "jobs-in-information-communication-technology",
    "Insurance & Superannuation": "jobs-in-insurance-superannuation",
    "Legal": "jobs-in-legal",
    "Manufacturing, Transport & Logistics": "jobs-in-manufacturing-transport-logistics",
    "Marketing & Communications": "jobs-in-marketing-communications",
    "Mining, Resources & Energy": "jobs-in-mining-resources-energy",
    "Real Estate & Property": "jobs-in-real-estate-property",
    "Retail & Consumer Products": "jobs-in-retail-consumer-products",
    "Sales": "jobs-in-sales",
    "Science & Technology": "jobs-in-science-technology",
    "Self Employment": "jobs-in-self-employment",
    "Sport & Recreation": "jobs-in-sport-recreation",
    "Trades & Services": "jobs-in-trades-services",
}

SEEK_CATEGORIES = [
    "Accounting",
    "Administration & Office Support",
    "Advertising, Arts & Media",
    "Banking & Financial Services",
    "Call Centre & Customer Service",
    "CEO & General Management",
    "Community Services & Development",
    "Construction",
    "Consulting & Strategy",
    "Design & Architecture",
    "Education & Training",
    "Engineering",
    "Farming, Animals & Conservation",
    "Government & Defence",
    "Healthcare & Medical",
    "Hospitality & Tourism",
    "Human Resources & Recruitment",
    "Information & Communication Technology",
    "Insurance & Superannuation",
    "Legal",
    "Manufacturing, Transport & Logistics",
    "Marketing & Communications",
    "Mining, Resources & Energy",
    "Real Estate & Property",
    "Retail & Consumer Products",
    "Sales",
    "Science & Technology",
    "Self Employment",
    "Sport & Recreation",
    "Trades & Services",
]
